### ISSUE TITLE
Create XRayInstrument

### ISSUE THREAD

**Issue by pokryfka** [pokryfka/aws-xray-sdk-swift#34]
PoC implemented in https://github.com/pokryfka/aws-xray-sdk-swift/pull/16

TODO:

- [ ] [map HTTP Span attributes to XRay segment HTTP](#22), depends on https://github.com/slashmo/gsoc-swift-tracing/issues/65
- [ ] Record exceptions, depends on https://github.com/slashmo/gsoc-swift-tracing/issues/90
- [ ] log `SpanEvent` timestamp and attributes
- [ ] log `SpanLink`
- [ ] implement `forceFlush` and `shutdown`, depends on https://github.com/slashmo/gsoc-swift-tracing/issues/85, see #21
- [ ] update `InstrumentationSystem` bootstrap in [`AWSXRayInstrumentExample `](Examples/Sources/AWSXRayInstrumentExample/main.swift), depends on https://github.com/slashmo/gsoc-swift-tracing/issues/86
- [ ] add example of instrumenting HTTP client (remove [`BetterHTTPClient`](https://github.com/pokryfka/aws-xray-sdk-swift/pull/16/files#diff-08d60a3228423c14cb685f91fbefaa84)), depends on https://github.com/slashmo/gsoc-swift-tracing/issues/95
- [ ] add example of passing baggage in NIO channel, depends on https://github.com/slashmo/gsoc-swift-tracing/issues/48
- [ ] document usage in README
